name: Verify the specified codebase

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    env:
      imageVersion: 'v25.09'
      module: 'github.com/scionproto/scion/'
      includePaths: '. ./gobra/stdlib-specs'
    steps:
      - name: Checkout the SCION repository
        uses: actions/checkout@v2
      - name: Check that the package gobra/utils is well-formed
        uses: viperproject/gobra-action@v25.09.1
        with:
          packages: 'gobra/utils'
          # Gobra only verifies files annotated with the header "// +gobra"
          headerOnly: '1'
          timeout: 2m
          imageVersion: ${{ env.imageVersion }}
          module: ${{ env.module }}
          includePaths: ${{ env.includePaths }}
      - name: Check that specifications of third-party libraries are well-formed
        uses: viperproject/gobra-action@v25.09.1
        with:
          projectLocation: 'scion/gobra/stdlib-specs'
          headerOnly: '1'
          # Check all package specifications in directory stdlib-specs
          recursive: '1'
          timeout: 10m
          imageVersion: ${{ env.imageVersion }}
          module: ${{ env.module }}
          includePaths: '. ../..' # relative to project location
      - name: Verify package `pkg/addr`
        uses: viperproject/gobra-action@v25.09.1
        with:
          packages: 'pkg/addr'
          headerOnly: '1'
          timeout: 2m
          imageVersion: ${{ env.imageVersion }}
          module: ${{ env.module }}
          includePaths: ${{ env.includePaths }}
      - name: Verify package `pkg/slayers/path`
        uses: viperproject/gobra-action@v25.09.1
        with:
          packages: 'pkg/slayers/path'
          headerOnly: '1'
          timeout: 2m
          imageVersion: ${{ env.imageVersion }}
          module: ${{ env.module }}
          includePaths: ${{ env.includePaths }}